/**
 * Created by 1021288 on 6/22/2017.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
        package myprojectbg;

/**
 *
 * @author Administrator
 */

        import java.sql.*;
        import java.util.Scanner;
        import javax.swing.*;
public class Newtc extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    String s;
    Boolean flg=false;
    /**
     * Creates new form demo2
     */
    public Newtc() {
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:testdsn1");
            stmt = con.createStatement();

        }catch(Exception e){System.out.println(e.toString());}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GA Tool");
        setIconImage(new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\myprojectbg1\\src\\icon1.jpg").getImage());
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setText("Enter Table Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 190, 27);

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel2.setText("Enter Functional Header");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 260, 27);

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel3.setText("Enter TestCase Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 260, 26);

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel4.setText("Enter TestCase Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 270, 29);

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel5.setText("Enter Expected Result");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 250, 28);

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel6.setText("Enter Requirement Criticality");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 320, 280, 29);

        jTextField1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 30, 190, 23);

        jTextField2.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 80, 190, 23);

        jTextField3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(350, 130, 190, 23);

        jTextField4.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(350, 190, 190, 23);

        jTextField5.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(350, 250, 190, 23);

        jCheckBox1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jCheckBox1.setText("Done");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(610, 30, 57, 25);

        jButton1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 430, 110, 33);

        jButton2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 430, 130, 33);

        jButton3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 430, 110, 33);

        jComboBox1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "critical", "must run ", "probable", "intermediate", "important" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 320, 190, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg7.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(evt.getSource()==jButton3)
        {
            ProjGA pg=new ProjGA();
            pg.show();
            pg.setSize(1000,800);
            this.hide();
            Existing ex=new Existing();
            ex.hide();
            //  ex.accept(s);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(evt.getSource()==jButton2)
        {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            //jTextField6.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    int id=1;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(evt.getSource()==jButton1)
        {
            if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"enter a value ");
                flg=true;
            }

            Scanner sc1=new Scanner(jTextField2.getText());
            while(sc1.hasNextInt())
            {
                sc1.next();
                JOptionPane.showMessageDialog(null,"please enter only valid string for functional header");
                flg=true;
            }

            Scanner sc2=new Scanner(jTextField3.getText());
            while(sc2.hasNextInt())
            {
                sc2.next();
                JOptionPane.showMessageDialog(null,"please enter only valid string for test case number");
                flg=true;
            }

            Scanner sc3=new Scanner(jTextField4.getText());
            while(sc3.hasNextInt())
            {
                sc3.next();
                JOptionPane.showMessageDialog(null,"please enter only valid string for test case description");
                flg=true;
            }

            Scanner sc4=new Scanner(jTextField5.getText());
            while(sc4.hasNextInt())
            {
                sc4.next();
                JOptionPane.showMessageDialog(null,"please enter only valid string for expected result");
                flg=true;
            }

            if(flg==false)
            {
                String str = (String)jComboBox1.getSelectedItem();
                try
                {
                    String qry="INSERT into "+s+" values(?,?,?,?,?,?)";
                    PreparedStatement pstmt=con.prepareStatement(qry);
                    pstmt.setInt(1,id);
                    pstmt.setString(2,jTextField2.getText());
                    pstmt.setString(3,jTextField3.getText());
                    pstmt.setString(4,jTextField4.getText());
                    pstmt.setString(5,jTextField5.getText());
                    pstmt.setString(6,str);

                    pstmt.executeUpdate();
                    id++;
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    //jTextField6.setText("");
                }catch(Exception e){System.out.println(e.toString());}
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if(evt.getSource()==jCheckBox1)
        {
            String str=jTextField1.getText();
            if(jCheckBox1.isSelected())
            {
                jTextField1.setEditable(false);
                s=jTextField1.getText();
                try
                {
                    boolean b=stmt.execute("create table "+s+"(id Integer,fun_header varchar(10),test_no varchar(10),test_desc varchar(50),expected_result varchar(50),req_criticality varchar(10))");

                    PreparedStatement pst=con.prepareStatement("insert into combotable (tablename) values(?)");
                    pst.setString(1,str);

                    pst.executeUpdate();

                }
                catch (Exception e){ System.out.println(e.toString());}
            }

            else
                jTextField1.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newtc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newtc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newtc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newtc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newtc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
